# Generated by Django 4.1 on 2022-09-02 15:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exp',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='available_rocks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=8),
        ),
    ]
