# Generated by Django 4.1 on 2022-10-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_user_available_rocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rock',
            name='image',
        ),
        migrations.AddField(
            model_name='rock',
            name='scin',
            field=models.IntegerField(default=0),
        ),
    ]
