# Generated by Django 4.0.6 on 2022-08-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rock',
            name='happiness_index',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rock',
            name='health_index',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rock',
            name='hunger_index',
            field=models.IntegerField(max_length=100),
        ),
    ]
